[package]
name = "bkmodel"
version = "0.1.0"
authors = ["Kenneth Perry (thothonegan) <thothonegan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
snafu = "0.6.10"
